dist: xenial

language: minimal

script:
- tools/travis-ci-script.sh || travis_terminate 1

before_deploy:
  - git tag continuous-deployment -f
  - git remote set-url origin https://${GITHUB_TOKEN}@github.com/jaxxzer/stm32-boilerplate
  - git push origin continuous-deployment -f

deploy:
  provider: releases
  api_key: ${GITHUB_TOKEN}
  file: stm32-boilerplate-examples.tar
  overwrite: true
  skip_cleanup: true
  on:
    branch: master
